spring:
  application:
    name: moni
  ai:
    chat:
      client:
        enabled: true
    openai:
      api-key: sk-vJbpCmfxfwp9zP3r9c4fCd15D3E64631892e107259B4Fe5a
      base-url: https://aihubmix.com
    mcp:
      server:
              name: moni-mcp-server
              version: 1.0.0
              type: sync
              sse-message-endpoint: /moni/mcp/messages
              capabilities:
                tool: true
              sse-endpoint: /moni/sse
  datasource:
    url: jdbc:sqlite:/Users/wanglongjun/project/moni/expense.db
  mail:
    host: smtp.qq.com
    port: 465
    username: 846179345@qq.com
    password: wbnolcjvquolbbjb
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  servlet:
    multipart:
          max-file-size: 10MB
moni:
  ai:
    openai:
      model: gpt-5
    gemini:
      model: gemini-2.5-pro
    deepseek:
      model: DeepSeek-V3.2-Exp-Think
    claude:
      model: claude-sonnet-4-20250514
    intent:
      model: gpt-5-nano
    extract:
      model: Qwen2.5-VL-72B-Instruct
  image:
    path: /Users/wanglongjun/project/moni/images
logging:
  level:
    root: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 7634
